INFO:root:App created!
INFO:root:App created!
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 52, in get_trends
    trends = tre(date)
  File "/Users/shaliko/gitProj/MoreTech_4/ML/model.py", line 462, in get_trends
    reader = DataReader(data_path=data_path)
  File "/Users/shaliko/gitProj/MoreTech_4/ML/model.py", line 61, in __init__
    with open(data_path) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: './data/result_acc.json'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:26:48] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 52, in get_trends
    trends = tre(date)
  File "/Users/shaliko/gitProj/MoreTech_4/ML/model.py", line 462, in get_trends
    reader = DataReader(data_path=data_path)
  File "/Users/shaliko/gitProj/MoreTech_4/ML/model.py", line 64, in __init__
    with open(data_path) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: './data/result_acc.json'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:28:01] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(trends), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:29:07] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(trends['trending']), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Series is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:31:40] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'get_trends' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:32:44] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'get_trends' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:35:57] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'get_trends' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:37:20] "[35m[1mGET /get_trends HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:54:56] "[33mGET /get_trends HTTP/1.1[0m" 404 -
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(trends(date))), 200
TypeError: trends_to_json() missing 1 required positional argument: 'trends'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:55:20] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(user_id, h.trends_to_json(trends(date))), 200
TypeError: trends_to_json() missing 1 required positional argument: 'trends'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:56:21] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:57:11] "GET /get_trends/1 HTTP/1.1" 200 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 05:58:34] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/backend/helpers.py", line 43, in trends_to_json
    return json.dump(dict_data, ensure_ascii=False)
TypeError: dump() missing 1 required positional argument: 'fp'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:03:19] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:04:14] "GET /get_trends/1 HTTP/1.1" 200 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:07:00] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:09:40] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type bytes is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:12:52] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:NewsAPI:Exception on /get_trends/1 [GET]
Traceback (most recent call last):
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaliko/gitProj/MoreTech_4/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/shaliko/gitProj/MoreTech_4/backend/app.py", line 53, in get_trends
    return jsonify(h.trends_to_json(user_id, trends(date))), 200
  File "/Users/shaliko/gitProj/MoreTech_4/backend/helpers.py", line 39, in trends_to_json
    dict_data['trends'].append(self.acc_clusters_dict[i]).encode('cp1251')
AttributeError: 'NoneType' object has no attribute 'encode'
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:14:04] "[35m[1mGET /get_trends/1 HTTP/1.1[0m" 500 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:15:01] "GET /get_trends/1 HTTP/1.1" 200 -
INFO:root:App created!
INFO:root:Run app!
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:16:38] "GET /get_trends/1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:16:44] "[33mGET /get_trends/2 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:17:04] "GET /get_trends/3 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Oct/2022 06:17:36] "GET /get_trends/1 HTTP/1.1" 200 -
